apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-sql-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  storageClassName: "" # Empty string must be explicitly set 
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: "/mnt/data" 