apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: senior
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc-mysql
      containers:
      - image: mysql:8.0
        name: mysql
        volumeMounts:
        - name: pvc
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: 0.5Gi
            cpu: 500m
          requests:
            memory: 0.5Gi
            cpu: 200m
        envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: my-secret-sql
      tolerations:
        - key: "db"
          operator: Equal
          value: only
          effect: "NoSchedule"

status: {}
