apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: web-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
