
# -------------------------------
# MongoDB (StatefulSet)
# -------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-ss
  namespace: db-namespace
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ss-pod
  template:
    metadata:
      labels:
        app: mongo-ss-pod
    spec:
      containers:
        - name: mongodb
          image: mongodb/mongodb-atlas-local:8.0.7
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-config
              mountPath: /data/configdb
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["mongod", "--bind_ip_all"]
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: mongo-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: db-namespace
spec:
  type: ClusterIP
  selector:
    app: mongo-ss-pod
  ports:
    - port: 27017
      targetPort: 27017
