---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota
  namespace: senior-namespace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "4"