apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-nginx
  name: service-nginx
  namespace: web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deployment-nginx

